import React, {useState, useEffect} from 'react';
import Head from 'next/head';
import * as S from '../styles/home';
import NavBar from '@/components/Navbar';
import Footer from '@/components/Footer';
import {relative} from 'path';


const Home = () => {

    return (
        <>
            <Head>
                <title>Zunne</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
                <link rel="icon" href="/LogoZunne.svg"/>
            </Head>
            <NavBar/>
            <S.Main>
                <S.ContainerPrincipal>
                    <S.SpanTitulo style={
                        {fontWeight: '400'}
                    }>Polinizando o empreendedorismo de
                        <br/><span style={
                            {
                                fontWeight: '700',
                                color: '#ff6514'
                            }
                        }>impacto positivo para transformar o futuro</span>
                    </S.SpanTitulo>
                    <div style={
                        {
                            display: 'flex',
                            flexDirection: 'column',
                            justifyContent: 'end',
                            alignItems: 'center',
                            position: 'relative'
                        }
                    }>
                        <S.BoxVideo></S.BoxVideo>
                        <S.BotaoInvestir style={
                            {
                                position: 'absolute',
                                top: '93%'
                            }
                        }>Quero investir!</S.BotaoInvestir>
                    </div>
                    <S.SpanPrimeiroTexto>O Zunne é um programa de investimento de impacto, que prioriza negócios de impacto positivo
                                                 liderados por mulheres, pessoas negras e/ou indígenas, com o intuito de erradicar a pobreza e
                                                  reduzir desigualdades no Norte e Nordeste do Brasil, democratizando o investimento de impacto.</S.SpanPrimeiroTexto>
                    <S.ContainerDuplo>
                        <img src='/abelha.svg'/>
                        <S.SpanTextoAbelha>Nossa inspiração vem da conexão com a natureza: as
                            <span style={
                                {color: '#f2ae13'}
                            }> abelhas </span>
                            e seu trabalho de polinização que simboliza ideias como: cooperação, lealdade, sabedoria, organização e trabalho.</S.SpanTextoAbelha>
                    </S.ContainerDuplo>
                    <S.ContainerTriplo>
                        <div style={
                            {
                                display: 'flex',
                                flexDirection: 'column',
                                height: '100%'
                            }
                        }>
                            <S.SpanTituloLaranja>O Problema</S.SpanTituloLaranja>
                            <S.SpanTextos style={
                                {textAlign: 'center'}
                            }>A desigualdade social afeta grande parte da população brasileira, mas o Norte e o Nordeste são as regiões que apresentam os piores índices de desenvolvimento humano.</S.SpanTextos>
                        </div>
                        <div style={
                            {
                                display: 'flex',
                                justifyContent: 'center',
                                alignItems: 'center',
                                width: '100%',
                                height: '100%'
                            }
                        }>
                            <div style={
                                {
                                    backgroundColor: '#ff6514',
                                    width: '4px',
                                    height: '70%'
                                }
                            }></div>
                        </div>
                        <div style={
                            {
                                display: 'flex',
                                flexDirection: 'column',
                                height: '100%'
                            }
                        }>
                            <S.SpanTituloLaranja>O Contexto</S.SpanTituloLaranja>
                            <S.SpanTextos style={
                                {textAlign: 'center'}
                            }>Segundo a Pipe Social, apenas 21% dos negócios de impacto estão na região Nordeste e Norte, e grande parte dos fundos de impact investing estão sediados na região Sudeste do país.</S.SpanTextos>
                        </div>
                    </S.ContainerTriplo>
                    <S.ContainerTriplo2 style={
                        {paddingLeft: '2rem'}
                    }>
                        <S.BoxReferencias>
                            <S.SpanTextosQuadrados>
                                Um estudo feito pela CB Insights mostra que 38% das startups faliram por conta de falta de dinheiro ou dificuldade de conseguir investimentos.
                            </S.SpanTextosQuadrados>
                            <S.SpanFonte>
                                Fonte: gazeta do povo - 22/04/2022
                            </S.SpanFonte>
                        </S.BoxReferencias>
                        <S.BoxReferencias>
                            <S.SpanTextosQuadrados>
                                De acordo com o mapa de negócios de impacto socioambiental, negócios administrados apenas por um time feminino tendem a receber menos recursos financeiros e outros apoios para evoluir na jornada.
                            </S.SpanTextosQuadrados>
                            <S.SpanFonte>
                                Fonte: gazeta do povo – 22/04/2022
                            </S.SpanFonte>
                        </S.BoxReferencias>
                        <S.BoxReferencias>
                            <S.SpanTextosQuadrados>
                                A maior parte das organizações com programas e iniciativas<br/>
                                que apoiam e investem em negócios de impacto se concentram<br/>
                                no sudeste, em especial no estado de são paulo.
                            </S.SpanTextosQuadrados>
                            <S.SpanFonte>
                                Fonte: guia 2.5 – quintessa
                            </S.SpanFonte>
                        </S.BoxReferencias>
                    </S.ContainerTriplo2>
                    <S.BoxLaranja>
                        <div style={{width: '35%', display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '1rem'}}>
                            <S.SpanTituloLaranja>A Solução</S.SpanTituloLaranja>
                            <S.SpanTextos style={{textAlign: 'left'}}>O Zunne propõe uma jornada transformadora para impulsionar negócios de impacto nas regiões Norte e Nordeste, com apoio financeiro, técnico e conexões estratégicas. <span style={{color: '#ff6514'}}>Cada investimento será uma semente plantada, cultivada e geradora de frutos que alimentam comunidades inteiras.</span></S.SpanTextos>
                            <S.BotaoInvestir>Quero investir!</S.BotaoInvestir>
                        </div>
                        <S.ImagemMulher src='/mulher.svg'/>
                    </S.BoxLaranja>
                    <div style={{width: '90%', border: '1px solid #ff6514', display: 'flex', gap: '4rem', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '2rem 0', borderRadius:'4rem'}}>
                        <S.SpanTitulo>O que são negócios de <span style={{color: '#ff6514'}}>impacto positivo?</span></S.SpanTitulo>
                        <S.ContainerDuplo style={{gridTemplateColumns: '40% 40%'}}>
                            <div>
                                <img src='/imagemArcoIris.svg'/>
                                <div style={{backgroundColor: '#ff6514', width: '100%', display: 'flex', justifyContent: 'center'}}>
                                    <S.SpanOnu>OBJETIVOS DE DESENVOLVIMENTO SUSTENTÁVEL &bull; ONU</S.SpanOnu>
                                </div>
                            </div>
                            <S.SpanTextosNegocios>São negócios interessados aqueles que direcionam ou têm intenção de direcionar seus modelos de negócio para a resolução de problemas socioambientais.<br/><br/>
                                Também nos orientamos pelos Objetivos de Desenvolvimento Sustentável até 2030 da ONU
                                <a href=''
                                    style={
                                        {color: '#ff6514', textDecoration: 'none'}
                                }>(clique aqui para conhecer)</a>.
                            </S.SpanTextosNegocios>
                        </S.ContainerDuplo>
                    </div>
                    <S.SpanTitulo>Esses são os <span style={{color: '#ff6514'}}>negócios da nossa colmeia!</span></S.SpanTitulo>
                    <S.ContainerCirculoCinza>
                        <S.DivCirculoCinza>
                            <S.CirculoCinza src='/Sucre.svg'/>
                            <S.BotaoTransparente>Sucré</S.BotaoTransparente>
                            <S.BotaoTransparente2><span style={{width: '100%'}}>Inserção da mulher nomercado de trabalho</span></S.BotaoTransparente2> 
                            <S.BotaoSaberMais>Quero investir!</S.BotaoSaberMais>
                        </S.DivCirculoCinza>
                        <S.DivCirculoCinza>
                            <S.CirculoCinza src='/RomaNegra.svg'/>
                            <S.BotaoTransparente>Roma Negra</S.BotaoTransparente>
                            <S.BotaoTransparente2><span style={{width: '100%'}}>Inserção no mercado de trabalho e impacto ambietal</span></S.BotaoTransparente2> 
                            <S.BotaoSaberMais>Quero investir!</S.BotaoSaberMais>
                        </S.DivCirculoCinza>
                        <S.DivCirculoCinza>
                            <S.CirculoCinza src='/MudaMeuMundo.svg' style={{objectFit: 'cover'}}/>
                            <S.BotaoTransparente>Muda Meu Mundo</S.BotaoTransparente>
                            <S.BotaoTransparente2><span style={{width: '100%'}}>Agricultura de impacto</span></S.BotaoTransparente2> 
                            <S.BotaoSaberMais>Quero investir!</S.BotaoSaberMais>
                        </S.DivCirculoCinza>
                    </S.ContainerCirculoCinza>
                    <S.SpanTitulo>Idealizadores</S.SpanTitulo>
                    <S.SpanTextosIdealizadores>O Programa Zunne é construído a muitas mãos a partir de um desejo em comum: sermos impulsionadores de uma economia mais justa e próspera para todos. Ele nasce da união e colaboração entre 3 organizações que são referência em incentivo a transformação social</S.SpanTextosIdealizadores>
                    <S.ContainerEmpresas>
                        <div style={{display: 'flex', flexDirection:'column', justifyContent: 'start', alignItems: 'center', height: '100%', gap: '2rem'}}>
                            <S.LogosEmpresas src='somos-um.png'/>
                            <S.SpanTextosDosIdealizadores>Somos uma articuladora de negócios de impacto que busca resolver problemas sociais e ambientais contribuindo para a construção de uma nova economia, mais justa e equilibrada, com pessoas conscientes, atuando em rede. Existimos para reduzir desigualdades e gerar oportunidades por meio dos negócios de impacto.</S.SpanTextosDosIdealizadores>
                        </div>
                        <div style={{display: 'flex', flexDirection:'column', justifyContent: 'start', alignItems: 'center', height: '100%', gap: '2rem'}}>
                            <S.LogosEmpresas src='yunus.png'/>
                            <S.SpanTextosDosIdealizadores>Aproveitamos o poder dos negócios sociais para resolver problemas urgentes do mundo, por meio da inovação social corporativa e da oferta de financiamento para pequenas e médias empresas de impacto. Temos um portfólio de crédito ativo com mais de 60 negócios sociais em 5 países – Brasil, Colômbia, Uganda, Quênia e Índia. No Brasil, já financiamos diversos projetos, com mais de R$ 22 milhões sob gestão.</S.SpanTextosDosIdealizadores>
                        </div>
                        <div style={{display: 'flex', flexDirection:'column', justifyContent: 'start', alignItems: 'center', height: '100%', gap: '2rem'}}>
                            <S.LogosEmpresas src='tre.png'/>
                            <S.SpanTextosDosIdealizadores>Viabilizamos investimentos com causa por meio de programas e soluções financeiras que desenvolvemos para nutrir negócios que geram impacto positivo e impulsionam transformações socioambientais. Já mobilizamos mais de R$ 15 milhões para 63 negócios com causa, por meio de uma engajada comunidade de +700 investidores!</S.SpanTextosDosIdealizadores>
                        </div>
                    </S.ContainerEmpresas>                
                </S.ContainerPrincipal>
            </S.Main>
            <Footer/>
        </>
    );
}

export default Home;
