import React, {useState, useEffect} from 'react';
import Head from 'next/head';
import * as S from '../styles/home';
import NavBar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { relative } from 'path';


const Home = () => {

    return (
        <>
            <Head>
                <title>Zunne</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>                
                <link rel="icon" href="/LogoZunne.svg"/>
            </Head>
            <NavBar/>
            <S.Main>   
                <S.ContainerPrincipal>
                    <S.SpanTitulo>Polinizando o empreendedorismo de <br/>impacto positivo para transformar o futuro</S.SpanTitulo>
                    <S.BotaoInvestir>Quero investir!</S.BotaoInvestir>
                    <S.SpanPrimeiroTexto>O Zunne é um programa de investimento de impacto, que prioriza negócios de impacto positivo
                         liderados por mulheres, pessoas negras e/ou indígenas, com o intuito de erradicar a pobreza e
                          reduzir desigualdades no Norte e Nordeste do Brasil, democratizando o investimento de impacto.</S.SpanPrimeiroTexto>
                    <S.BoxVideo></S.BoxVideo>
                    <S.ContainerDuplo>
                        <img src='/abelha.svg'/>
                        <S.SpanTextos>Nossa inspiração vem da conexão com a natureza: as abelhas e seu trabalho de polinização que simboliza ideias como: cooperação, lealdade, sabedoria, organização e trabalho.</S.SpanTextos>
                    </S.ContainerDuplo>
                    <S.ContainerDuplo>
                        <S.BoxLaranja>
                            <S.ImagemBoxLaranja src='/BoxLaranja.svg'/>
                            <div style={{position: 'absolute', display: 'flex', flexDirection: 'column'}}>
                                <S.SpanTituloLaranja>O Problema</S.SpanTituloLaranja>
                                <S.SpanTextos style={{textAlign: 'center'}}>A desigualdade social afeta grande parte da população brasileira, mas o Norte e o Nordeste são as regiões que apresentam os piores índices de desenvolvimento humano.</S.SpanTextos>
                            </div>
                        </S.BoxLaranja>
                        <S.BoxLaranja>
                            <S.ImagemBoxLaranja src='/BoxLaranja.svg'/>
                            <div style={{position: 'absolute', display: 'flex', flexDirection: 'column'}}>
                                <S.SpanTituloLaranja>O Contexto</S.SpanTituloLaranja>
                                <S.SpanTextos style={{textAlign: 'center'}}>Segundo a Pipe Social, apenas 21% dos negócios de impacto estão na região Nordeste e Norte, e grande parte dos fundos de impact investing estão sediados na região Sudeste do país.</S.SpanTextos>
                            </div>
                        </S.BoxLaranja>
                    </S.ContainerDuplo>
                    <S.ContainerDuplo style={{paddingLeft: '2rem'}}>
                        <div style={{display: 'flex', flexDirection: 'column', height: '100%'}}>
                            <S.SpanTextos>
                                Um estudo feito pela CB Insights mostra que 38% das startups faliram por conta de falta de dinheiro ou dificuldade de conseguir investimentos.
                            </S.SpanTextos>
                            <S.SpanFonte>
                                Fonte: gazeta do povo - 22/04/2022
                            </S.SpanFonte>
                        </div>
                        <div style={{display: 'flex', flexDirection: 'column', height: '100%'}}>
                            <S.SpanTextos>
                                De acordo com o mapa de negócios de impacto socioambiental, negócios administrados apenas por um time feminino tendem a receber menos recursos financeiros e outros apoios para evoluir na jornada.
                            </S.SpanTextos>
                            <S.SpanFonte>
                                Fonte: gazeta do povo – 22/04/2022
                            </S.SpanFonte>
                        </div>
                    </S.ContainerDuplo>
                    <div style={{width: '72%', display: 'flex', flexDirection: 'column'}}>
                        <S.SpanTextos>
                            A maior parte das organizações com programas e iniciativas<br/> que apoiam e investem em negócios de impacto se concentram<br/> no sudeste, em especial no estado de são paulo.
                        </S.SpanTextos>
                        <S.SpanFonte>
                            Fonte: guia 2.5 – quintessa
                        </S.SpanFonte>
                    </div>                    
                    <S.BoxLaranja style={{width: '30%'}}>
                        <S.ImagemBoxLaranja src='/BoxLaranja.svg'/>
                        <div style={{position: 'absolute', display: 'flex', flexDirection: 'column'}}>
                            <S.SpanTituloLaranja>A Solução</S.SpanTituloLaranja>
                            <S.SpanTextos style={{textAlign: 'center'}}>O Zunne propõe uma jornada transformadora para impulsionar negócios de impacto nas regiões Norte e Nordeste, com apoio financeiro, técnico e conexões estratégicas. Cada investimento será uma semente plantada, cultivada e geradora de frutos que alimentam comunidades inteiras.</S.SpanTextos>
                        </div>
                    </S.BoxLaranja>
                    <S.BotaoInvestir>Quero investir!</S.BotaoInvestir>
                    <S.SpanTitulo>O que são negócios de impacto positivo?</S.SpanTitulo>
                    <S.ContainerDuplo style={{gap: '0rem'}}>
                        <img src='/imagemArcoIris.svg'/>
                        <S.SpanTextos>São negócios interessados aqueles que direcionam ou têm intenção de direcionar seus modelos de negócio para a resolução de problemas socioambientais.<br/><br/>
                        Também nos orientamos pelos Objetivos de Desenvolvimento Sustentável até 2030 da ONU <a href='' style={{color: '#57575A'}}>(clique aqui para conhecer)</a>.
                        </S.SpanTextos>
                    </S.ContainerDuplo>
                    <S.SpanTitulo>Esses são os negócios da nossa colmeia!</S.SpanTitulo>
                    <S.ContainerCirculoCinza>
                        <div>
                            <S.CirculoCinza></S.CirculoCinza>
                        </div>
                        <div>
                            <S.CirculoCinza></S.CirculoCinza>
                        </div>
                        <div>
                            <S.CirculoCinza></S.CirculoCinza>
                        </div>
                        <div>
                            <S.CirculoCinza></S.CirculoCinza>
                        </div>
                    </S.ContainerCirculoCinza>
                    <S.SpanTitulo>Idealizadores</S.SpanTitulo>
                    <S.SpanTextosIdealizadores>O Programa Zunne é construído a muitas mãos a partir de um desejo em comum: sermos impulsionadores de uma economia mais justa e próspera para todos. Ele nasce da união e colaboração entre 3 organizações que são referência em incentivo a transformação social</S.SpanTextosIdealizadores>
                </S.ContainerPrincipal>
            </S.Main>
            <Footer/>
        </>
    );
}

export default Home;

